# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
import numpy as np

In [6]:
np.random.randint(0, 20, size = (4, 7))

array([[ 4, 10, 12, 18,  3,  0, 12],
       [ 0,  8,  6,  4,  2,  1, 11],
       [ 8, 17,  1, 10, 17,  6,  8],
       [ 7,  1,  9, 11,  6, 16, 11]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [7]:
np.random.randint(0, 10, size = (8, 10))

array([[3, 7, 9, 1, 9, 6, 9, 3, 2, 9],
       [7, 8, 9, 7, 8, 3, 1, 5, 3, 9],
       [1, 4, 2, 3, 9, 4, 1, 5, 4, 1],
       [1, 4, 7, 9, 4, 7, 6, 8, 7, 8],
       [0, 9, 4, 7, 8, 4, 5, 2, 4, 6],
       [6, 1, 2, 9, 6, 8, 1, 9, 0, 2],
       [5, 2, 4, 5, 9, 2, 1, 7, 5, 1],
       [9, 2, 8, 5, 1, 4, 7, 9, 6, 2]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [10]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [102]:
def Print(a):
    for elem in a:
        print(elem)


# Выполнение Лабораторной работы №1

#1 Файл minutes_n_ingredients.csv содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива numpy типа int32, используя np.loadtxt. Выведите на экран первые 5 строк массива.

In [111]:
import numpy as np
array = np.loadtxt('data\minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows = 1)
print("ID \t minutes \t n_ingridients")
print(array[:5])

ID 	 minutes 	 n_ingridients
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


#2 Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [47]:
meanValues = np.mean(array[:,1:],axis=0, dtype = np.float32, keepdims = False)
minValues = array[:,1:].min(axis=0)
maxValues = array[:,1:].max(axis=0)
medianValues = np.median(array[:,1:], axis=0)
print(f"Среднее значение:   {meanValues} \nЗначения минимума:  {minValues}\nЗначения максимума: {maxValues} \nМедианные значения: {medianValues}")

Среднее значение:   [2.1575027e+04 9.0552797e+00] 
Значения минимума:  [0 1]
Значения максимума: [2147483647         39] 
Медианные значения: [40.  9.]


№3 Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля  𝑞 0.75

In [48]:
quantileValue=np.quantile(array[:,1], q=0.75,axis=0)
print(quantileValue)
maskArray =array[:,1]<= quantileValue
quantiledArray = array[maskArray]
print("Массив ограниченный сверху квантилем 0.75:")
quantiledArray

65.0
Массив ограниченный сверху квантилем 0.75:


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

#4 Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1

In [121]:
counter= 0
counter=np.count_nonzero(array[:,1]==0)
print(array[array[:,1]==0].shape)
print(array[array[:,1]==0])
np.place(array, array==0, [1])

print(f"Для {counter} рецептов указана продолжительность, равная нулю:")


(0, 3)
[]
Для 0 рецептов указана продолжительность, равная нулю:


#5 Посчитайте, сколько уникальных рецептов находится в датасете.

In [120]:
recepieid = array[:, [0]]
print(np.unique(recepieid))
print(np.unique(recepieid).size)
print("Всего рецептов:",array[:,0].shape[0])
print(f"В датасете находится {np.unique(array[:,0]).shape[0]} уникальных рецептов")

[    38     41     43 ... 537458 537485 537671]
100000
Всего рецептов: 100000
В датасете находится 100000 уникальных рецептов


#6 Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [119]:
uniqueRecipes= np.unique(array[:,2])
print(f"В датасете присутствуют {np.unique(array[:,2]).shape[0]} уникальных значений кол-ва ингридиентов")
print(f"Значения: {uniqueRecipes}")

В датасете присутствуют 37 уникальных значений кол-ва ингридиентов
Значения: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


#7 Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [122]:
newArray=array[array[:,2]<=5]
print("Массив, содержащий информацию только о рецептах, состоящих не более чем из 5 ингредиентов: \n", newArray, "\nФорма массива:\n", newArray.shape)

Массив, содержащий информацию только о рецептах, состоящих не более чем из 5 ингредиентов: 
 [[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]] 
Форма массива:
 (17262, 3)


#8 Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [123]:
averrageIngridients = array[:,2]/array[:,1]
print(f"Массив средних значений для датасета: \n {averrageIngridients}")
print(f"Максимальное значение этой величины для всего датасета: \n {averrageIngridients.max()}")
#Print(averrageIngridients)

Массив средних значений для датасета: 
 [0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
Максимальное значение этой величины для всего датасета: 
 24.0


#9 Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [45]:
SortedArray=array[array[:, 1].argsort(axis=0)]#Сортировка исходного массива
SortedArray=(SortedArray[:-101:-1])#Обратный срез 100 элементов массива по кол-ву ингридиентов
print(SortedArray.shape)#проверка формы среза
#print(SortedArray) # проверка
averrageValue =np.mean(SortedArray[:,2])#Вычисление среднего по 3 столбцу массива
print (f"Ответ: Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью равно {averrageValue}")

(100, 3)
Ответ: Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью равно 8.89


#10 Выберите случайным образом и выведите информацию о 10 различных рецептах

In [25]:
numRows = array.shape[0]
random = np.random.choice(numRows, 
                                  size=10, 
                                  replace=False)

print("ID \t minutes \t n_ingridients")
print(array[random, :])

ID 	 minutes 	 n_ingridients
[[480495      5      5]
 [ 80467     75     12]
 [136406     40      8]
 [ 27839     17     10]
 [ 48238     65      6]
 [419045     20      3]
 [357469     50     13]
 [260913     60     13]
 [ 10766     30      5]
 [ 54866     20     17]]


#11 Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [9]:
averrageV= array[:,2].mean()
changedArray=array[array[:,2]<averrageV]
print(changedArray.shape)
value= changedArray.shape[0]/array.shape[0]
percents=value*100
print(f"Ответ: {percents} - процент рецептов, кол-во ингредиентов в которых меньше среднего", percents)

(58802, 3)
Ответ: 58.802 - процент рецептов, кол-во ингредиентов в которых меньше среднего 58.802


#12 Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [4]:
x1 = array[:,1]<= 20 
x2 = array[:,2]<=5
extraColumn= np.logical_and(x1, x2)
extraColumn=np.asanyarray(extraColumn, dtype="int64")
extraColumn=np.reshape(extraColumn, (-1, 1))
a1= np.hstack((array, extraColumn))
print(a1)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


#13 Выведите процент "простых" рецептов в датасете

In [5]:
simpleNum=a1[a1[:,3]==1].shape[0]
allNum= a1.shape[0]
percents= simpleNum/allNum* 100
#print(simpleNum, allNum) проверка значений
print("Ответ: %3.3f%% - процент \"простых\"рецептов" %percents)

Ответ: 9.552% - процент "простых"рецептов


#14 Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [8]:
print(a1.shape)
fast = array[a1[:,1]< 10]
medium = array[np.logical_and(a1[:,1]>=10, a1[:,1]<=20)]
long = array[a1[:,1] >20]
size= min(map(len, [fast, medium, long]))
result = np.vstack(([fast[:size,:]],[medium[:size,:]], [long[:size, :]]))
#column1= np.full((fast.shape[0], 1), 1)
#column2= np.full((medium.shape[0], 1), 2)
#column3= np.full((long.shape[0],1), 3)
#fast= np.hstack((fast, column1))
#medium =np.hstack((medium, column2))
#long =np.hstack((long, column3))
#final = np.concatenate([fast,medium], axis=0)
#final =  np.concatenate([final,long], axis=0)
#typeColumn=np.asanyarray(extraColumn, dtype="int32")
#typeColumn=np.reshape(typeColumn, (-1, 1))
#arr1=np.hstack((a1, typeColumn))
result

(100000, 4)


array([[[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [  4747,      0,      9],
        [370915,      5,      4]],

       [[ 94746,     10,      6],
        [ 33941,     18,      9],
        [446597,     15,      5],
        ...,
        [331810,     13,     12],
        [275677,     15,      8],
        [282714,     15,      6]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [ 24549,     70,      6],
        [449468,     50,     11],
        [ 28830,     65,     13]]])